### PR TITLE
Add configs/ahmubashshir

### PR DESCRIPTION
**Pull request by ahmubashshir**
Signed-off-by: Mubashshir <ahmubashshir@gmail.com>

### CODE REVIEW

**Comment by romkatv** [comment]
What's the motivation for adding this config to zsh-bench?

**Comment by ahmubashshir** [comment]
Some extreme config splitting, maybe!?
	Mubashshir

**Comment by romkatv** [comment]
What do you mean by that?

**Comment by ahmubashshir** [comment]
I tried to split tasks(env initializations/plugin loading/...) into 
separate files, and loaded them using zsh-defer 😛
	Mubashshir

**Comment by romkatv** [comment]
Cool I guess.

Did you send this PR with a suggestion that I merge it? If so, why do you think I should merge it? In other words, how does this PR improve zsh-bench?

**Comment by ahmubashshir** [comment]
So that someone won't follow my footstep tweaking so much and instead 
use zsh4humans, if he wants to tweak even after getting warned by this, 
this can be an example :3
	Mubashshir

**Comment by romkatv** [comment]
Are you suggesting that I merge this as an example of a complex and bad config? This doesn't seem worthwhile. There is virtually unlimited supply of complex and bad configs.

**Comment by ahmubashshir** [comment]
ok, you can close it then 😛
	Mubashshir

**Comment by romkatv** [comment]
In the future when you send a PR, provide an explanation why you think the PR is an improvement for the project. It'll save time.

**Pull request closed without merging**
