### PR TITLE
completion module is optional in prezto and zim

### PR DESCRIPTION
**Pull request by ericbn**
So it can be disabled if you want a more barebones set up, like the other "+" configurations.

### CODE REVIEW

**Comment by romkatv** [comment]
I see what you did there but where do we draw the line? At the limit we can disable everything and the config degenerates into a plain DIY. Besides, is this representative of what real users of prezto and zim would do? I think the current version is more representative and more in line with what prezto and zim want from their users to do.

**Comment by ericbn** [comment]
I was just trying to get their configs closer to the other configs too, for a fairer comparison between the different benchmarks.

Nothing is stopping zplug users from using the zimfw/completion module if they want to, as well as nothing is forcing Zim users to use it, just to give an example.

I'm just thinking of having more similar configurations, where that's possible. Will "real users" really just use the bare bones configurations of "diy++" or "powerlevel10k"? I was not thinking in terms of questions like these, just is terms of comparable configurations.

**Comment by romkatv** [comment]
> Will "real users" really just use the bare bones configurations of "diy++" or "powerlevel10k"? I was not thinking in terms of questions like these, just is terms of comparable configurations.

Configs such as "powerlevel10k", "compsys" or "zsh-syntax-highlighting" measure the performance of the respective features in isolation.

"diy++", "zim+" and other configs in this category match real life configs that enable tmux, completions, syntax highlighting, autosuggestions and powerlevel10k. If a zim user wanted to enable these features, "zim+" is how they would likely do it. These configs don't go out of their way trying to disable built-in features or to replace them with manual code. For example, "ohmyzsh+" doesn't disable the built-in libs even though this can be done and it does speed things up.

If you want "zim+" to be changed, you'll need to change zim -- either its code or documentation.

**Comment by ericbn** [comment]
I see the approach zsh-bench is taking, and it seems like it's comparing the times of different things. For example, it's comparing plugin managers using different sets of plugins: zinit, zplug and zcomet with zsh-users/zsh-syntax-highlighting, zsh-users/zsh-autosuggestions and romkatv/powerlevel10k, and zim with those plus zimfw/completion.

I can update Zim's documentation to make it clearer that it can be used solely as a plugin manager.

**Comment by romkatv** [comment]
> I see the approach zsh-bench is taking, and it seems like it's comparing the times of different things.

[This section](https://github.com/romkatv/zsh-bench#plugin-managers) compares different configs that provide at least these features: tmux, compsys, syntax highlighting, auto suggestions, and git prompt.

**Comment by ericbn** [comment]
Sure, I see all boxes are checked, and they mean the same thing for all configurations, except for "compsys". Some are just calling `compinit`, others are setting many zstyles in addition to that.

**Comment by romkatv** [comment]
> Sure, I see all boxes are checked, and they mean the same thing for all configurations, except for "compsys".

"compsys" checkbox means the same thing in all configs. Its meaning is documented here: https://github.com/romkatv/zsh-bench/blob/d776974c34b9a96f38f6fd042d78c2f1373df1a6/README.md?plain=1#L116

> Some are just calling `compinit`, others are setting many zstyles in addition to that.

All premade configs do things that aren't reflected by the capability checkboxes. This is mentioned in the docs: https://github.com/romkatv/zsh-bench/blob/d776974c34b9a96f38f6fd042d78c2f1373df1a6/README.md?plain=1#L317-L318

**Comment by romkatv** [comment]
Closing as WAI.

**Pull request closed without merging**
